import ContactSection from "@/components/ContactSection/ContactSection";
import Features from "@/components/Features/Features";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import TheApp from "@/components/TheApp/TheApp";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <TheApp />
      <Features />
      <ContactSection />
      <Footer />
    </>
  );
}
